FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .

# مرحلة التشغيل (أصغر وأسرع)
FROM node:20-alpine
WORKDIR /app
COPY --from=build /app .
EXPOSE 8000
CMD ["node", "src/index.js"]