# بنستخدم نسخة خفيفة من Node
FROM node:18-alpine

# الفولدر اللي الكود هيعيش فيه جوه الحاوية
WORKDIR /app

# بننقل ملفات التعريف الأول عشان الـ Caching
COPY package*.json ./

# بنسطب المكتبات
RUN npm install

# بننقل باقي الكود
COPY . .

# البورت اللي الخدمة هتشتغل عليه
EXPOSE 5002

# أمر التشغيل
CMD ["node", "index.js"]