apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: restaurant-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: food-delivery-restaurant:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/food_delivery_restaurants"
        - name: PORT
          value: "5001"
        - name: JWT_SECRET
          value: "my_super_secret"