apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: food-delivery-user:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/food_delivery_users"
        - name: PORT
          value: "5000"
        - name: JWT_SECRET
          value: "my_super_secret"